<a href="https://colab.research.google.com/github/dtorrejon/data-science-from-scratch/blob/master/capitulo_03_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##FUNDAMENTOS NUMPY

###Rendimiento de numpy

Comparama los tiempos de ejecucion, para realizar una operacion sobre un array de numpy y uno nativo de python


In [2]:
import numpy as np
my_array = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_array2 = my_array*2
%timeit my_list2 = [element * 2 for element in my_list]

2.73 ms ± 984 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
122 ms ± 17.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


###ndarray en numpy (objeto array n-dimensional)

####Operaciones basicas

In [3]:
data = np.array([[1.5,-0.1,3.],[0.,-3.,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

####Obtener la dimension de un array

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

####Obyener tipo de datos de un array

In [18]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int64')

####Generar un array de ceros

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
#se puede usar np.empty pero no se aseura que devuelva todo ceros al no inicializarlo
np.empty((2,3,2))

array([[[4.66842134e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

####Devolver un rango de valores

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Tipos de datos

In [30]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([4,5,6], dtype = np.int64)

In [33]:
arr1.dtype

dtype('float64')

In [35]:
arr2.dtype

dtype('int64')

####Conversion de tipos

In [37]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.dtype

dtype('int64')

In [38]:
float_arr = arr.astype(np.float64)

In [40]:
arr = np.array([1.2,5., 6.7, 55423,64523,9.])
arr.astype(np.int32)

array([    1,     5,     6, 55423, 64523,     9], dtype=int32)

In [43]:
numeric_strings = np.array(["1.25","-9.6","42"], dtype = np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

###Aritmetica con Arrays