<a href="https://colab.research.google.com/github/dtorrejon/data-science-from-scratch/blob/master/capitulo_03_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##FUNDAMENTOS NUMPY

###Rendimiento de numpy

Comparama los tiempos de ejecucion, para realizar una operacion sobre un array de numpy y uno nativo de python


In [2]:
import numpy as np
my_array = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_array2 = my_array*2
%timeit my_list2 = [element * 2 for element in my_list]

2.71 ms ± 226 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
137 ms ± 20.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


###ndarray en numpy (objeto array n-dimensional)

####Operaciones basicas

In [3]:
data = np.array([[1.5,-0.1,3.],[0.,-3.,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [6]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

####Obtener la dimension de un array

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

####Obyener tipo de datos de un array

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int64')

####Generar un array de ceros

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
#se puede usar np.empty pero no se aseura que devuelva todo ceros al no inicializarlo
np.empty((2,3,2))

array([[[6.75305358e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

####Devolver un rango de valores

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#
### Tipos de datos

In [16]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([4,5,6], dtype = np.int64)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

####Conversion de tipos

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.dtype

dtype('int64')

In [20]:
float_arr = arr.astype(np.float64)

In [21]:
arr = np.array([1.2,5., 6.7, 55423,64523,9.])
arr.astype(np.int32)

array([    1,     5,     6, 55423, 64523,     9], dtype=int32)

In [22]:
numeric_strings = np.array(["1.25","-9.6","42"], dtype = np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])



####Aritmetica con Arrays

In [24]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [28]:
1//arr

array([[1., 0., 0.],
       [0., 0., 0.]])

In [30]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [32]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [33]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

###Indexado y slicing

In [34]:
arr = np.arange(10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [43]:
arr_slice[:]=64
arr_slice

array([64, 64, 64])

In [44]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
arr2d[2]

array([7, 8, 9])

In [46]:
arr2d[0][2]

3

In [47]:
arr2d[0,2]

3